cmake_minimum_required (VERSION 3.5)

# Symbol to generate
set(filename ${SYMBOL})

# Create header for CPP file
file(WRITE ${OUTPUT_C} "/* Autogenerated by bin2c */\n\n")
file(APPEND ${OUTPUT_C} "#include \"${filename}.h\"\n\n")

# Create header of H file
file(WRITE ${OUTPUT_H} "/* Autogenerated by bin2c */\n\n")
file(APPEND ${OUTPUT_H} "#pragma once\n")
file(APPEND ${OUTPUT_H} "#include <string>\n\n")

# Read file content as string
file(READ ${INPUT_FILE} filedata)

# Escape special characters for raw string
string(REPLACE "\\" "\\\\" filedata "${filedata}")
string(REPLACE "\"" "\\\"" filedata "${filedata}")

# Append data to c file using raw string literal
file(APPEND ${OUTPUT_C} "const std::string ${filename} = R\"shader_content(\n${filedata}\n)shader_content\";\n\n")

# Append extern definitions to h file
file(APPEND ${OUTPUT_H} "extern const std::string ${filename};\n\n")